#!/usr/bin/env python3
"""Generate the one-to-one Mojo loaders for the Python agent contract.

Every ``ai-agent-contract/src/ai_orchestrator/**/*.py`` module receives a
homologous ``ai-agent-runtime/src/contracts/ai_orchestrator/**/*.mojo`` loader.
The generated registry eagerly imports those modules once when ``agentd``
starts and keeps their ``PythonObject`` handles alive for the process lifetime.
"""

from __future__ import annotations

from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
PYTHON_ROOT = ROOT / "ai-agent-contract" / "src"
PYTHON_PACKAGE = PYTHON_ROOT / "ai_orchestrator"
MOJO_ROOT = ROOT / "ai-agent-runtime" / "src" / "contracts"
GENERATED_HEADER = "# Generated by scripts/generate_agent_contract_loaders.py.\n"


def module_name(path: Path) -> str:
    parts = list(path.relative_to(PYTHON_ROOT).with_suffix("").parts)
    if parts[-1] == "__init__":
        parts.pop()
    return ".".join(parts)


def mojo_path(path: Path) -> Path:
    return MOJO_ROOT / path.relative_to(PYTHON_ROOT).with_suffix(".mojo")


def loader_module(module: str) -> str:
    return f"contracts.{module}"


def loader_source(module: str) -> str:
    return (
        GENERATED_HEADER
        + f'"""Loader for the Python contract module ``{module}``."""\n\n'
        + "from std.python import Python, PythonObject\n\n\n"
        + "def load() raises -> PythonObject:\n"
        + f'    return Python.import_module("{module}")\n'
    )


def registry_source(modules: list[str]) -> str:
    loader_imports = "\n".join(
        f"from {loader_module(module)} import load as load_{index:03d}"
        for index, module in enumerate(modules)
    )
    loads = "\n".join(
        f'    registry.store("{module}", load_{index:03d}())'
        for index, module in enumerate(modules)
    )
    return (
        GENERATED_HEADER
        + '"""Eagerly loaded and process-lifetime cache of Python modules."""\n\n'
        + "from std.python import Python, PythonObject\n\n\n"
        + loader_imports
        + "\n\n\n"
        + "struct PythonContractRegistry:\n"
        + "    var modules: PythonObject\n"
        + "    var count: Int\n\n"
        + "    def __init__(out self) raises:\n"
        + '        self.modules = Python.import_module("builtins").dict()\n'
        + "        self.count = 0\n\n"
        + "    def store(mut self, name: String, var module: PythonObject) raises:\n"
        + "        self.modules[name] = module^\n"
        + "        self.count += 1\n\n"
        + "    def get(self, name: String) raises -> PythonObject:\n"
        + "        return self.modules.__getitem__(name)\n\n\n"
        + "def expected_contract_module_count() -> Int:\n"
        + f"    return {len(modules)}\n\n\n"
        + "def load_all_contract_modules() raises -> PythonContractRegistry:\n"
        + "    var registry = PythonContractRegistry()\n"
        + loads
        + "\n    return registry^\n"
    )


def main() -> None:
    python_files = sorted(PYTHON_PACKAGE.rglob("*.py"))
    modules = [module_name(path) for path in python_files]
    expected: set[Path] = set()

    for path, module in zip(python_files, modules, strict=True):
        target = mojo_path(path)
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(loader_source(module), encoding="utf-8")
        expected.add(target)

    registry = MOJO_ROOT / "registry.mojo"
    registry.parent.mkdir(parents=True, exist_ok=True)
    registry.write_text(registry_source(modules), encoding="utf-8")
    expected.add(registry)

    for stale in MOJO_ROOT.rglob("*.mojo"):
        if stale not in expected:
            stale.unlink()

    print(f"generated {len(python_files)} loaders and {registry.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
