# Generated by scripts/generate_agent_contract_loaders.py.
"""Loader for the Python contract module ``ai_orchestrator.adapter.messaging.kafka.producer``."""

from std.python import Python, PythonObject


def load() raises -> PythonObject:
    return Python.import_module("ai_orchestrator.adapter.messaging.kafka.producer")
